name: dart_server
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 path: ^1.4.1
 html: ^0.13.3+3
 postgres: ^1.0.2
 intl: ^0.15.7
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  source_gen: ^0.9.4+1
  build_runner: ^1.2.8
  intl_translation: ^0.17.0
transformers:
  -intl_translation:
    $include: lib/locale.dart